[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trails-lca"
authors = [
  { name="Romain Sacchi", email="romain.sacchi@psi.ch" },
]
maintainers = [
  { name="Romain Sacchi", email="romain.sacchi@psi.ch" }
]
description = "Temporal routing and aggregation of impacts across life-cycle systems"
readme = "README.md"
dynamic = ["dependencies", "version"]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.10, <3.12"

[project.urls]
source = "https://github.com/Laboratory-for-Energy-Systems-Analysis/trails"
homepage = "https://github.com/Laboratory-for-Energy-Systems-Analysis/trails"
tracker = "https://github.com/Laboratory-for-Energy-Systems-Analysis/trails/issues"

[project.optional-dependencies]
testing = [
    "setuptools",
    "pytest",
]

docs = [
    "sphinx-rtd-theme"
]

umfpack = [
    "scikit-umfpack"
]

[tool.setuptools]
license-files = ["LICENSE.md"]
include-package-data = true

[tool.setuptools.packages.find]
include = ["trails*"]
namespaces = true

[tool.setuptools.package-data]
trails = ["data/**/*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "trails.__version__"}

[tool.pytest.ini_options]
markers = [
    # marks tests that require ecoinvent (to be disabled on Travis)
    "ecoinvent",
    "forked",
    "serial"
]
norecursedirs = [
    "dist",
    "build",
    ".tox"
]
testpaths = ["tests/*.py"]

[tool.flake8]
# Some sane defaults for the code style checker flake8
max_line_length = 88
extend_ignore = ["E203", "W503"]
exclude = [
    ".tox",
    "build",
    "dist",
    ".eggs",
    "docs/conf.py",
]
